import { ChartColumn, Home, NotepadText, Package, PackagePlus, Settings, ShoppingBag, UserCheck, UserPlus, Users } from "lucide-react";
import { projectsData } from "@/data";

import ProfileImage from "@/assets/profile-image.jpg";
import ProductImage from "@/assets/product-image.jpg";

export const navbarLinks = [
    {
        title: "Dashboard",
        links: [
            {
                label: "Dashboard",
                icon: Home,
                path: "/",
            },
            {
                label: "Analytics",
                icon: ChartColumn,
                path: "/analytics",
            },
            {
                label: "Reports",
                icon: NotepadText,
                path: "/reports",
            },
        ],
    },
    {
        title: "Customers",
        links: [
            {
                label: "Customers",
                icon: Users,
                path: "/customers",
            },
            {
                label: "New customer",
                icon: UserPlus,
                path: "/new-customer",
            },
            {
                label: "Verified customers",
                icon: UserCheck,
                path: "/verified-customers",
            },
        ],
    },
    {
        title: "Products",
        links: [
            {
                label: "Products",
                icon: Package,
                path: "/products",
            },
            {
                label: "New product",
                icon: PackagePlus,
                path: "/new-product",
            },
            {
                label: "Inventory",
                icon: ShoppingBag,
                path: "/inventory",
            },
        ],
    },
    {
        title: "Settings",
        links: [
            {
                label: "Settings",
                icon: Settings,
                path: "/settings",
            },
        ],
    },
];

// Example for monthly trend
export const monthlyData = [
  { name: "Jan 2025", carsOpen: 5, obsOpen: 2, kpiAchieved: 85, billability: 80 },
  { name: "Feb 2025", carsOpen: 4, obsOpen: 3, kpiAchieved: 87, billability: 82 },
  // ...
];

export const yearlyData = [
  { name: "2024", carsOpen: 50, obsOpen: 20, kpiAchieved: 86, billability: 81 },
  { name: "2025", carsOpen: 60, obsOpen: 25, kpiAchieved: 88, billability: 83 },
  // ...
];

export const recentSalesData = [
    {
        id: 1,
        name: "Olivia Martin",
        email: "olivia.martin@email.com",
        image: ProfileImage,
        total: 1500,
    },
    {
        id: 2,
        name: "James Smith",
        email: "james.smith@email.com",
        image: ProfileImage,
        total: 2000,
    },
    {
        id: 3,
        name: "Sophia Brown",
        email: "sophia.brown@email.com",
        image: ProfileImage,
        total: 4000,
    },
    {
        id: 4,
        name: "Noah Wilson",
        email: "noah.wilson@email.com",
        image: ProfileImage,
        total: 3000,
    },
    {
        id: 5,
        name: "Emma Jones",
        email: "emma.jones@email.com",
        image: ProfileImage,
        total: 2500,
    },
    {
        id: 6,
        name: "William Taylor",
        email: "william.taylor@email.com",
        image: ProfileImage,
        total: 4500,
    },
    {
        id: 7,
        name: "Isabella Johnson",
        email: "isabella.johnson@email.com",
        image: ProfileImage,
        total: 5300,
    },
];

export const topProducts = [
    {
        number: 1,
        name: "Wireless Headphones",
        image: ProductImage,
        description: "High-quality noise-canceling wireless headphones.",
        price: 99.99,
        status: "In Stock",
        rating: 4.5,
    },
    {
        number: 2,
        name: "Smartphone",
        image: ProductImage,
        description: "Latest 5G smartphone with excellent camera features.",
        price: 799.99,
        status: "In Stock",
        rating: 4.7,
    },
    {
        number: 3,
        name: "Gaming Laptop",
        image: ProductImage,
        description: "Powerful gaming laptop with high-end graphics.",
        price: 1299.99,
        status: "In Stock",
        rating: 4.8,
    },
    {
        number: 4,
        name: "Smartwatch",
        image: ProductImage,
        description: "Stylish smartwatch with fitness tracking features.",
        price: 199.99,
        status: "Out of Stock",
        rating: 4.4,
    },
    {
        number: 5,
        name: "Bluetooth Speaker",
        image: ProductImage,
        description: "Portable Bluetooth speaker with deep bass sound.",
        price: 59.99,
        status: "In Stock",
        rating: 4.3,
    },
    {
        number: 6,
        name: "4K Monitor",
        image: ProductImage,
        description: "Ultra HD 4K monitor with stunning color accuracy.",
        price: 399.99,
        status: "In Stock",
        rating: 4.6,
    },
    {
        number: 7,
        name: "Mechanical Keyboard",
        image: ProductImage,
        description: "Mechanical keyboard with customizable RGB lighting.",
        price: 89.99,
        status: "In Stock",
        rating: 4.7,
    },
    {
        number: 8,
        name: "Wireless Mouse",
        image: ProductImage,
        description: "Ergonomic wireless mouse with precision tracking.",
        price: 49.99,
        status: "In Stock",
        rating: 4.5,
    },
    {
        number: 9,
        name: "Action Camera",
        image: ProductImage,
        description: "Waterproof action camera with 4K video recording.",
        price: 249.99,
        status: "In Stock",
        rating: 4.8,
    },
    {
        number: 10,
        name: "External Hard Drive",
        image: ProductImage,
        description: "Portable 2TB external hard drive for data storage.",
        price: 79.99,
        status: "Out of Stock",
        rating: 4.5,
    },
];

export const overviewData = [
  { name: "Jan", carsOpen: 5, obsOpen: 2, kpiAchieved: 85, billability: 80 },
  { name: "Feb", carsOpen: 4, obsOpen: 3, kpiAchieved: 87, billability: 82 },
  // ...add more months
];

export const projectInfo = {
  srNo: 1,
  projectNo: "5648888",
  projectTitle: "Study for Flare Gas Recovery",
  client: "Google",
  projectManager: "Ragav Nair",
  startDate: "12/3/2025",
  closingDate: "12/8/2026",
  extension: "Yes",
  manhourUsed: 1200,
  manhourBalance: 800,
};

export const timelineData = [
  { name: "Audit Phase 1", progress: 80, status: "On Track", daysRemaining: 30 },
  { name: "Client Review", progress: 100, status: "Completed", daysRemaining: 0 },
  { name: "Final Report", progress: 40, status: "Delayed", daysRemaining: -5 },
  // Add more items as needed
];

export const projectStatusData = [
  {
    srNo: 1,
    projectNo: "5648888",
    title: "Study for Flare Gas Recovery",
    client: "Google",
    manager: "Ragav Nair",
    startDate: "12/3/2025",
    closingDate: "12/8/2026",
    extension: "Yes",
    manhourUsed: 1200,
    manhourBalance: 800,
    billability: 85,
    qualityPlanStatus: "Rev",
    qualityPlanIssueDate: "12/1/2025",
    audit1: "Done",
    audit2: "Pending",
    audit3: "Pending",
    audit4: "Pending",
    clientAudit1: "Done",
    clientAudit2: "Pending",
    auditDelayDays: 2,
    carsOpen: 5,
    carsDelayedClosingDays: 1,
    carsClosed: 3,
    obsOpen: 2,
    obsDelayedClosingDays: 1,
    obsClosed: 1,
    kpiAchieved: 90,
  },
  {
    srNo: 2,
    projectNo: "5648999",
    title: "Pipeline Integrity Study",
    client: "Microsoft",
    manager: "Priya Singh",
    startDate: "01/2/2026",
    closingDate: "11/12/2026",
    extension: "No",
    manhourUsed: 900,
    manhourBalance: 600,
    billability: 80,
    qualityPlanStatus: "Issued",
    qualityPlanIssueDate: "01/3/2026",
    audit1: "Done",
    audit2: "Done",
    audit3: "Pending",
    audit4: "Pending",
    clientAudit1: "Pending",
    clientAudit2: "Pending",
    auditDelayDays: 0,
    carsOpen: 2,
    carsDelayedClosingDays: 0,
    carsClosed: 5,
    obsOpen: 1,
    obsDelayedClosingDays: 0,
    obsClosed: 3,
    kpiAchieved: 95,
  },
  {
    srNo: 3,
    projectNo: "5649001",
    title: "Energy Efficiency Audit",
    client: "Amazon",
    manager: "John Doe",
    startDate: "03/5/2026",
    closingDate: "09/10/2026",
    extension: "No",
    manhourUsed: 700,
    manhourBalance: 500,
    billability: 78,
    qualityPlanStatus: "Issued",
    qualityPlanIssueDate: "03/6/2026",
    audit1: "Done",
    audit2: "Pending",
    audit3: "Pending",
    audit4: "Pending",
    clientAudit1: "Pending",
    clientAudit2: "Pending",
    auditDelayDays: 1,
    carsOpen: 3,
    carsDelayedClosingDays: 1,
    carsClosed: 2,
    obsOpen: 1,
    obsDelayedClosingDays: 0,
    obsClosed: 2,
    kpiAchieved: 88,
  },
  {
    srNo: 4,
    projectNo: "5649002",
    title: "Water Treatment Study",
    client: "Tesla",
    manager: "Sara Lee",
    startDate: "04/1/2026",
    closingDate: "10/15/2026",
    extension: "Yes",
    manhourUsed: 1100,
    manhourBalance: 400,
    billability: 82,
    qualityPlanStatus: "Rev",
    qualityPlanIssueDate: "04/2/2026",
    audit1: "Done",
    audit2: "Done",
    audit3: "Pending",
    audit4: "Pending",
    clientAudit1: "Done",
    clientAudit2: "Pending",
    auditDelayDays: 0,
    carsOpen: 4,
    carsDelayedClosingDays: 2,
    carsClosed: 4,
    obsOpen: 2,
    obsDelayedClosingDays: 1,
    obsClosed: 2,
    kpiAchieved: 92,
  },
  {
    srNo: 5,
    projectNo: "5649003",
    title: "Safety Compliance Review",
    client: "Apple",
    manager: "Michael Chan",
    startDate: "05/10/2026",
    closingDate: "12/20/2026",
    extension: "No",
    manhourUsed: 950,
    manhourBalance: 350,
    billability: 75,
    qualityPlanStatus: "Issued",
    qualityPlanIssueDate: "05/12/2026",
    audit1: "Done",
    audit2: "Done",
    audit3: "Done",
    audit4: "Pending",
    clientAudit1: "Pending",
    clientAudit2: "Pending",
    auditDelayDays: 3,
    carsOpen: 2,
    carsDelayedClosingDays: 0,
    carsClosed: 6,
    obsOpen: 1,
    obsDelayedClosingDays: 0,
    obsClosed: 4,
    kpiAchieved: 89,
  },
  {
    srNo: 6,
    projectNo: "5649004",
    title: "Environmental Impact Assessment",
    client: "Meta",
    manager: "Linda Park",
    startDate: "06/15/2026",
    closingDate: "01/25/2027",
    extension: "Yes",
    manhourUsed: 1300,
    manhourBalance: 700,
    billability: 83,
    qualityPlanStatus: "Rev",
    qualityPlanIssueDate: "06/16/2026",
    audit1: "Done",
    audit2: "Pending",
    audit3: "Pending",
    audit4: "Pending",
    clientAudit1: "Done",
    clientAudit2: "Pending",
    auditDelayDays: 2,
    carsOpen: 6,
    carsDelayedClosingDays: 2,
    carsClosed: 2,
    obsOpen: 3,
    obsDelayedClosingDays: 1,
    obsClosed: 2,
    kpiAchieved: 87,
  },
  {
    srNo: 7,
    projectNo: "5649005",
    title: "Process Optimization",
    client: "Netflix",
    manager: "David Kim",
    startDate: "07/20/2026",
    closingDate: "02/28/2027",
    extension: "No",
    manhourUsed: 800,
    manhourBalance: 600,
    billability: 79,
    qualityPlanStatus: "Issued",
    qualityPlanIssueDate: "07/21/2026",
    audit1: "Done",
    audit2: "Done",
    audit3: "Pending",
    audit4: "Pending",
    clientAudit1: "Pending",
    clientAudit2: "Pending",
    auditDelayDays: 0,
    carsOpen: 3,
    carsDelayedClosingDays: 0,
    carsClosed: 5,
    obsOpen: 2,
    obsDelayedClosingDays: 0,
    obsClosed: 3,
    kpiAchieved: 91,
  },
  // ...add more projects here
];
